# Generated by Django 4.2.7 on 2023-11-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LottoGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=10),
                ),
                ("numbers", models.JSONField(blank=True, null=True)),
                ("n1", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n2", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n3", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n4", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n5", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n6", models.SmallIntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNumbers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numbers", models.JSONField(blank=True, null=True)),
                ("n1", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n2", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n3", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n4", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n5", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                ("n6", models.SmallIntegerField(blank=True, max_length=2, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="usernumbers", to="lotto.lottogame"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usernumbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
