# Generated by Django 4.2.7 on 2023-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0002_alter_usernumbers_n1_alter_usernumbers_n2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lottogame",
            name="n1",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="n2",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="n3",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="n4",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="n5",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="n6",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
