# Generated by Django 4.2.7 on 2023-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0003_alter_lottogame_n1_alter_lottogame_n2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernumbers",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("6", "6"), ("5", "5"), ("4", "4"), ("3", "3"), ("2", "2"), ("1", "1"), ("0", "0")],
            ),
        ),
    ]
