# Generated by Django 4.2.7 on 2023-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0004_usernumbers_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernumbers",
            name="status",
            field=models.CharField(
                choices=[
                    ("6", "6"),
                    ("5", "5"),
                    ("4", "4"),
                    ("3", "3"),
                    ("2", "2"),
                    ("1", "1"),
                    ("0", "0"),
                    ("OPEN", "Open"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
