# Generated by Django 4.2.7 on 2023-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0005_alter_usernumbers_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lottogame",
            options={"ordering": ["-date"], "verbose_name": "Lotto game", "verbose_name_plural": "Lotto games"},
        ),
        migrations.AlterModelOptions(
            name="usernumbers",
            options={"verbose_name": "User numbers", "verbose_name_plural": "User numbers"},
        ),
        migrations.AlterField(
            model_name="lottogame",
            name="status",
            field=models.CharField(choices=[("OPEN", "Open"), ("CLOSED", "Closed")], default="OPEN", max_length=10),
        ),
    ]
