# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0006_alter_lottogame_options_alter_usernumbers_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lottogame",
            name="n1",
        ),
        migrations.RemoveField(
            model_name="lottogame",
            name="n2",
        ),
        migrations.RemoveField(
            model_name="lottogame",
            name="n3",
        ),
        migrations.RemoveField(
            model_name="lottogame",
            name="n4",
        ),
        migrations.RemoveField(
            model_name="lottogame",
            name="n5",
        ),
        migrations.RemoveField(
            model_name="lottogame",
            name="n6",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n1",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n2",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n3",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n4",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n5",
        ),
        migrations.RemoveField(
            model_name="usernumbers",
            name="n6",
        ),
        migrations.AlterField(
            model_name="usernumbers",
            name="numbers",
            field=models.JSONField(),
        ),
    ]
