# Generated by Django 4.2.7 on 2023-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lotto", "0007_remove_lottogame_n1_remove_lottogame_n2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottogame",
            name="n1",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lottogame",
            name="n2",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lottogame",
            name="n3",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lottogame",
            name="n4",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lottogame",
            name="n5",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lottogame",
            name="n6",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n1",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n2",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n3",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n4",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n5",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernumbers",
            name="n6",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
