# Generated by Django 4.2.7 on 2023-12-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lotto", "0009_remove_lottogame_n1_remove_lottogame_n2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LottoCoupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("6", "6"),
                            ("5", "5"),
                            ("4", "4"),
                            ("3", "3"),
                            ("2", "2"),
                            ("1", "1"),
                            ("0", "0"),
                            ("OPEN", "Open"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("numbers", models.JSONField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lottocoupons", to="lotto.lottogame"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lottocoupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lotto coupon",
                "verbose_name_plural": "Lotto coupons",
            },
        ),
        migrations.DeleteModel(
            name="UserNumbers",
        ),
    ]
